# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Compilar, testar e implantar o aplicativo JAVA dentro da AZURE - 84pedidos-api

on: #Gatilho para executar a pipeline. 
  push: #A pipeline será executada após um PUSH no repositório 
    branches: #O push deverá ser feito na branch main
      - main #Nome da branch
  workflow_dispatch: #Executar o worfklow

jobs: #Etapas realizadas pela pipeline
  build: #Etapa de compilação do projeto
    name: Compilação da aplicação JAVA
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Configurar a versão do JAVA
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Compilar o projeto com Maven
        run: mvn clean install

      - name: Faz o Upload do pacote compilado para implantacao
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    name: Implantar a aplicação na AZURE
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Baixar o pacote do build para implantação
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Fazer login na AZURE
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AFD2ACAAFCCD45FCB2361064C6CBCD90 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5BEF86353BF548CD9410954FBB674612 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ECFE9EECD0AC44F0BEE5F401C6BA89F4 }}

      - name: Implantação do projeto na AZURE
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '84pedidos-api'
          slot-name: 'Production'
          package: '*.jar'
          